### ISSUE TITLE
Publishing on Flathub

### ISSUE THREAD

**Issue by alexkdeveloper** [dida-code/opstakultura#1]
I like this app!
Are you planning to publish this app on Flathub?

**Comment by dida-code** [comment]
yes, I plan to publish it, I will update it during the day, so you can take a look and if you have any suggestions, write... my plan is to insert as many questions as possible so that there are 50 questions during one game...

**Comment by dida-code** [comment]
Maybe it wouldn't be bad to make it in one more language so that the user can choose which language he wants to play in... but honestly I don't think I know how to do it yet

**Comment by alexkdeveloper** [comment]
Hi!

I think it's best to publish the source code of the application in English and put your native language in the po folder.   In particular, the file with questions (questions.json) must be translated into English.

After publishing the application, you can expect the application to be translated into other languages from free translators. 

This should be done simply because most open source applications are distributed in English.

**Comment by alexkdeveloper** [comment]
For the convenience of translation, I would recommend using Poedit.

**Comment by alexkdeveloper** [comment]
In addition, to use the full power of collaborative translation, you can try to connect your project to [Weblate](https://weblate.org/ru/). But I think that for this it is necessary that there are at least several hundred words in the application database.

**Comment by dida-code** [comment]
thanks, I'm going to start translating and when I'm done I might need a little help to publish the app on flathub... I'm not clear about those steps...

**Comment by dida-code** [comment]
I updated the app and switched to English.

**Comment by alexkdeveloper** [comment]
Great! Now you need to reissue the release or create a new one. It seems to me that it is better to make a reissue, because the application has not been published anywhere yet.   

Then you can start publishing on Flathub.

**Comment by alexkdeveloper** [comment]
Here you can read about the publication of the application:
https://docs.flathub.org/docs/for-app-authors/submission

All this can be done without resorting to console commands. Github allows you to perform all the basic operations with repositories through the web interface.  All you have to do is go to your fork of the flathub repository and create a branch there with a name similar to your application ID. Next, you need to create a file with the manifest of your application in a new branch. After all these actions, you can safely send a new merge request.

In addition, you can also read here:
https://discourse.flathub.org/t/dont-understand-the-instructions-to-create-a-flathub/3395

**Comment by dida-code** [comment]
I followed your instructions and I hope I did a good job. How long to wait for the application to be published?

**Comment by dida-code** [comment]
And can you tell me what about this:
Please confirm your submission meets all the criteria

I have read the [App Requirements](https://docs.flathub.org/docs/for-app-authors/requirements) and [App Maintenance](https://docs.flathub.org/docs/for-app-authors/maintanance) pages.
My pull request follows the instructions at [App Submission](https://docs.flathub.org/docs/for-app-authors/submission).
I am using only the minimal set of permissions. (If not, please explain each non-standard permission.)
All assets referenced in the manifest are redistributable by any party. If not, the unredistributable parts are using an extra-data source type.
I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. Link:
I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
Any additional patches or files have been submitted to the upstream projects concerned. (If not, explain why.)

Do i need to round everything up...?

**Comment by alexkdeveloper** [comment]
The speed of request processing depends on the complexity of the application and on the problems encountered during assembly. There are other factors, for example, whether the developer has prepared his application well for working in an isolated environment.  And how many people are currently making requests. For simple applications, requests are usually processed quickly.

**Comment by alexkdeveloper** [comment]
You can check all the boxes at the beginning of the request.

**Comment by dida-code** [comment]
I built the app via build bot for test and it works but I got a message from contributor:
"the PR should be done against the new-PR branch which is what triggered the closing when I changed it."
When I try to create a new PR I get the following message:
"There isn't anything to compare.
flathub:new-pr and dida-code:OpstaKultura are entirely different commit histories."
and again from contributor
"you need to rebase on the new-pr branch first"
what this means?

**Comment by alexkdeveloper** [comment]
Is it possible to reopen an old PR?
It seems to me there should be a button for rebasing, but I could be wrong.

If it doesn't work with the old PR, then try opening a new request in a new branch called io.github.dida_code.OpstaKultura

**Comment by dida-code** [comment]
I have got this message:
Closed with unmerged commits
This pull request is closed, but the dida-code:OpstaKultura branch has unmerged commits. You can delete this branch if you wish.
If you wish, you can also delete this fork of flathub/flathub in the [settings](https://github.com/dida-code/flathub/settings?confirm_delete=yes).

I don't see a button for rebasing anywhere

**Comment by alexkdeveloper** [comment]
I see that the case with the publication of the application is moving towards completion. Soon it will be possible to congratulate you on the release of the first application.

I have a little problem. The latest versions of the [Zodiac](https://flathub.org/en/apps/io.github.alexkdeveloper.zodiac) app have started behaving strangely. I briefly described the problem on the [forum](https://discourse.flathub.org/t/unstable-operation-of-the-application-after-the-update/5281), but I have not received an answer yet.

Could you test the app yourself? Create a horoscope for different folders several times and launch the file manager by clicking on the button in the header. It is important to choose different directories because the problem sometimes appears or not. Launching the file manager may also work, or it may not work. 

I can't say exactly what this problem might be related to, maybe something was updated incorrectly. This has never happened before. That's why I need to run the test on another system. I don't have that option. Thank you.

**Comment by dida-code** [comment]
is it version 1.0.7?
in this version, the application works as it should, I saved at least 5 files in different folders and it always worked as it should

**Comment by alexkdeveloper** [comment]
Thanks!
Does the file manager open a folder from the program?
What operating system and environment are you using?

**Comment by dida-code** [comment]
Linux Mint 21.2 x86_64
through the file manager, I choose the location where I want to save the data and it works as it should

**Comment by dida-code** [comment]
"launch the file manager by clicking on the button in the header"
but file manager is the button in the lower right corner

**Comment by dida-code** [comment]
did i understand your problem correctly?

**Comment by alexkdeveloper** [comment]
On the results page, there is an icon in the header that allows you to open a folder with saved files. This button is only available on the results page.

The button in the input field opens the folder selection window. This button is only available on data entry pages.

**Comment by dida-code** [comment]
Ok, on the result page, file manager opens the project where it was recorded with no problem.. i tried now with 5 different folders

**Comment by alexkdeveloper** [comment]
Great! Thank you very much again!

So the problem lies somewhere in the bowels of my system. But this is not entirely accurate.
By the way, Linux Mint is a great choice. A reliable and fairly stable system.

**Comment by dida-code** [comment]
I guess you know, you can make a live os on an external hard drive, a good thing where you can test applications outside your os

**Comment by alexkdeveloper** [comment]
Yes, I know about it. But at the moment I have too small an external drive, and it is not enough to install flatpak. 

It is also possible to install the system next to an existing one, but there is a chance that something may go wrong and the computer will stop booting at all.  

It is better to buy a larger disk.

**Comment by alexkdeveloper** [comment]
Congratulations!
Your app has appeared on Flathub!

**Comment by dida-code** [comment]
thank you, you helped me a lot, I wouldn't have been able to manage on my own
